// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFexNxglYsZkw56evJgRdiyh_Z_ILw9Bo',
    appId: '1:830579859783:web:103c6288be1ec826626c62',
    messagingSenderId: '830579859783',
    projectId: 'prakflutterfirebase-e79ad',
    authDomain: 'prakflutterfirebase-e79ad.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-e79ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAbdYiZoRf-fBofSyRGmSanFOYHcqrL90',
    appId: '1:830579859783:android:b92ccc611464832f626c62',
    messagingSenderId: '830579859783',
    projectId: 'prakflutterfirebase-e79ad',
    storageBucket: 'prakflutterfirebase-e79ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuskeT_jv8Vlf2oT-NaIhnk3_Uo4QXO10',
    appId: '1:830579859783:ios:dae711e469822751626c62',
    messagingSenderId: '830579859783',
    projectId: 'prakflutterfirebase-e79ad',
    storageBucket: 'prakflutterfirebase-e79ad.appspot.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuskeT_jv8Vlf2oT-NaIhnk3_Uo4QXO10',
    appId: '1:830579859783:ios:dae711e469822751626c62',
    messagingSenderId: '830579859783',
    projectId: 'prakflutterfirebase-e79ad',
    storageBucket: 'prakflutterfirebase-e79ad.appspot.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFexNxglYsZkw56evJgRdiyh_Z_ILw9Bo',
    appId: '1:830579859783:web:e076c41056af45b9626c62',
    messagingSenderId: '830579859783',
    projectId: 'prakflutterfirebase-e79ad',
    authDomain: 'prakflutterfirebase-e79ad.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-e79ad.appspot.com',
  );
}
